name: starwars_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.0.dev <4.0.0'

dependencies:
  build_runner: ^2.3.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.0
  get_it: ^7.2.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  generate: true
