name: starwars_app
description: A Flutter app to consume SWAPI- The Star Wars API

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-429.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  beamer: ^1.5.3
  provider: ^6.0.4
  responsive_framework: ^0.2.0
  rxdart: ^0.27.3
  flex_color_scheme: ^6.1.1

  auto_route: ^3.2.4
  cloud_firestore: ^3.1.10
  connectivity_plus: ^2.2.1
  dartz: ^0.10.1
  dio: ^4.0.6
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1

  flutter_flavorizr: ^2.1.2
  flutter_html: ^2.2.1
  flutter_riverpod: ^1.0.3
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.4
  hooks_riverpod: ^1.0.3
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1
  riverpod: ^1.0.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  anim_search_bar: ^2.0.2
  flash: ^2.0.3+2
  custom_radio_grouped_button: ^2.1.2
  firebase_auth_mocks: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: null
  build_runner: ^2.1.8
  lint: ^1.8.2
  auto_route_generator: ^3.2.3

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  injectable_generator: null
  mockito: ^5.1.0
  state_notifier_test: ^0.0.5
  retrofit_generator: null

flutter:
  uses-material-design: true
  generate: true